etcd-cpp-apiv3/etcd-cpp-apiv3

.github/workflows/build-test.yml, README.md, etcd/Client.hpp, security-config/.gitignore, security-config/openssl.cnf, security-config/reset-ca.sh, security-config/setup-ca.sh, src/Client.cpp, tst/EtcdSyncTest.cpp, tst/SecurityChannelTest.cpp
=> Support secure transport and certificate-based authentication.

README.md
Fix a minor mistake in installation instruction.
=> Update README.md shell command

etcd/Value.hpp, src/Value.cpp
class Value has some legacy useless code, remove such code.
=> class Value: remove useless code

etcd/Client.hpp, etcd/SyncClient.hpp, etcd/v3/Action.hpp, src/Client.cpp, src/SyncClient.cpp, src/v3/Action.cpp, src/v3/AsyncDeleteAction.cpp, src/v3/AsyncGetAction.cpp, src/v3/AsyncWatchAction.cpp, tst/EtcdTest.cpp
=> List/delete/watch on exact range.

etcd/Watcher.hpp, src/Watcher.cpp, tst/WatcherTest.cpp
Follow-up work on #51, and fixes #50.
=> Watch on range by specifying `rang_end`.

etcd/Response.hpp, etcd/v3/AsyncLeaseAction.hpp, src/KeepAlive.cpp, src/v3/AsyncLeaseAction.cpp, tst/WatcherTest.cpp
=> Optimize the implementation of error handling in keep alive.

etcd/Client.hpp, tst/EtcdTest.cpp
=> Expose the etcdv3::detail::string_plus_one method.

etcd/v3/action_constants.hpp, src/v3/Action.cpp, src/v3/AsyncDeleteAction.cpp, src/v3/AsyncGetAction.cpp, src/v3/AsyncLeaseAction.cpp, src/v3/AsyncWatchAction.cpp, src/v3/action_constants.cpp
On behalf of Asplund, Rickard, thanks!
=> Avoid duplicate const string tags.

README.md
Add some brief doc to answer the question in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/73
=> Add a brief doc and sample code describing how a watcher can re-connect to etcd server after disconnected

.github/workflows/build-test.yml, README.md, etcd/Client.hpp, etcd/Response.hpp, etcd/SyncClient.hpp, etcd/Value.hpp, etcd/v3/Action.hpp, etcd/v3/AsyncElectionAction.hpp, etcd/v3/AsyncElectionResponse.hpp, etcd/v3/AsyncLockAction.hpp, etcd/v3/AsyncLockResponse.hpp, etcd/v3/AsyncWatchAction.hpp, etcd/v3/V3Response.hpp, etcd/v3/action_constants.hpp, proto/CMakeLists.txt, proto/v3election.proto, src/Client.cpp, src/Response.cpp, src/SyncClient.cpp, src/v3/AsyncElectionAction.cpp, src/v3/AsyncElectionResponse.cpp, src/v3/AsyncLockResponse.cpp, src/v3/V3Response.cpp, src/v3/action_constants.cpp, tst/ElectionTest.cpp
=> Implements "v3election.proto" APIs.

.github/workflows/build-test.yml, src/Client.cpp, src/v3/AsyncElectionAction.cpp, src/v3/AsyncLeaseAction.cpp, src/v3/AsyncWatchAction.cpp, tst/MemLeakTest.cpp
=> Fixes memory leak in shutting down gRPC streams.

etcd/Response.hpp, etcd/v3/V3Response.hpp, src/Response.cpp, src/v3/AsyncWatchAction.cpp, src/v3/AsyncWatchResponse.cpp, src/v3/V3Response.cpp
=> Include compact revision for cancelled watch response.

README.md, etcd/Client.hpp, etcd/KeepAlive.hpp, etcd/SyncClient.hpp, etcd/Watcher.hpp, src/Client.cpp, src/KeepAlive.cpp, src/SyncClient.cpp, src/Watcher.cpp, tst/CMakeLists.txt
=> Allow specifying the auth token TTL when auth with password.

.github/workflows/build-deb-package.yml, .github/workflows/cancel.yaml
=> Build the deb package and upload to artifacts.

CMakeLists.txt
Signed-off-by: siyuan0322 <siyuan0322@gmail.com>
=> Bump cmake minimum required version to 3.3

README.md, etcd/Watcher.hpp, src/Watcher.cpp, tst/EtcdSyncTest.cpp, tst/EtcdTest.cpp
=> Use int64_t for etcd revisions/indexes.

README.md, etcd/Client.hpp, etcd/Response.hpp, etcd/SyncClient.hpp, etcd/v3/Action.hpp, src/KeepAlive.cpp, src/Response.cpp, src/SyncClient.cpp, src/Watcher.cpp, src/v3/Action.cpp, tst/LockTest.cpp
Implements the long-standing missing piece about setting timeout for grpc requests.
=> Implements the timeout feature to the etcd client.

README.md, etcd/Client.hpp, etcd/Response.hpp, etcd/SyncClient.hpp, etcd/v3/action_constants.hpp, src/Response.cpp, src/SyncClient.cpp, src/v3/AsyncCompareAndDeleteAction.cpp, src/v3/AsyncCompareAndSwapAction.cpp, src/v3/AsyncDeleteResponse.cpp, src/v3/AsyncRangeResponse.cpp, src/v3/AsyncSetAction.cpp, src/v3/AsyncTxnAction.cpp, src/v3/AsyncUpdateAction.cpp, src/v3/action_constants.cpp, tst/AuthTest.cpp, tst/EtcdTest.cpp, tst/SecurityChannelTest.cpp
=> Taking error code from grpc.

etcd/Client.hpp, etcd/Response.hpp, etcd/SyncClient.hpp, etcd/v3/V3Response.hpp, src/Client.cpp, src/Response.cpp, src/SyncClient.cpp, src/v3/AsyncLeaseResponse.cpp, src/v3/V3Response.cpp, tst/AuthTest.cpp, tst/ElectionTest.cpp, tst/EtcdSyncTest.cpp, tst/EtcdTest.cpp, tst/LockTest.cpp, tst/MemLeakTest.cpp, tst/RewatchTest.cpp, tst/SecurityChannelTest.cpp, tst/TransactionTest.cpp, tst/WatcherTest.cpp
=> Implements the "etcdctl lease list" functionality

CMakeLists.txt, etcd/Client.hpp, etcd/SyncClient.hpp, src/Client.cpp, src/SyncClient.cpp
=> Reliable macro condition to adapt to different version of gRPC.

.github/workflows/build-deb-package.yml, .github/workflows/build-test.yml, .github/workflows/centos-latest.yml
latest runner info in here, https://github.com/actions/runner-images
=> ci: update action runners

etcd/v3/AsyncLeaseAction.hpp, src/v3/AsyncLeaseAction.cpp
=> Fixes the deadlock in keep alive

.github/workflows/build-test.yml, README.md, etcd/KeepAlive.hpp, src/KeepAlive.cpp, tst/KeepAliveTest.cpp
=> Fixes the Check() error when if next refresh is not triggered yet

CMakeLists.txt, src/CMakeLists.txt
=> Improve the cmake script for better compatibility

.github/workflows/build-test.yml, tst/ForkTest.cpp
=> Test etcd client from forked child process

README.md, etcd/Watcher.hpp, etcd/v3/action_constants.hpp, src/v3/AsyncDeleteAction.cpp, src/v3/AsyncRangeAction.cpp, src/v3/AsyncWatchAction.cpp, src/v3/action_constants.cpp, tst/EtcdTest.cpp, tst/WatcherTest.cpp
=> Fixes bugs in ls/rmdir/watch for processing range end.

src/v3/AsyncWatchAction.cpp, tst/WatcherTest.cpp
=> Fixes the wrong key setup in watcher

README.md, src/v3/AsyncElectionAction.cpp, tst/CampaignTest.cpp
=> Enhance the campaign test and document the behaviour when timeout is set

src/v3/AsyncLeaseAction.cpp
=> Fixes a bug in lease action when grpc timeout is set

.github/workflows/build-test.yml, CMakeLists.txt, README.md, src/CMakeLists.txt
=> Add an option `BUILD_ETCD_CORE_ONLY=ON/OFF` to select the runtime

CMakeLists.txt
=> The grpc_cpp_plugin may failed to be found

etcd/Client.hpp, etcd/SyncClient.hpp, etcd/v3/Action.hpp, src/Client.cpp, src/SyncClient.cpp, src/v3/AsyncRangeAction.cpp, tst/EtcdTest.cpp
=> Get and list keys with specified revision.

.github/workflows/build-test.yml, etcd/Client.hpp, etcd/Response.hpp, etcd/SyncClient.hpp, etcd/v3/Action.hpp, etcd/v3/AsyncGRPC.hpp, etcd/v3/Member.hpp, etcd/v3/V3Response.hpp, etcd/v3/action_constants.hpp, src/Client.cpp, src/Response.cpp, src/SyncClient.cpp, src/Value.cpp, src/v3/AsyncGRPC.cpp, src/v3/Member.cpp, src/v3/V3Response.cpp, src/v3/action_constants.cpp, tst/EtcdMemberTest.cpp
=> Add the cluster manager api.
