src/v3/AsyncGetAction.cpp

Set a proper upper bound for `ls` request, and remove the default sort options.

---

README.md
etcd/KeepAlive.hpp
src/KeepAlive.cpp
tst/LockTest.cpp

Handling (or checking) possible failure in lease's KeepAlive.

---

README.md
src/KeepAlive.cpp

Implement a KeepAliveResponse callback, allows KeepAlive users to
detect expiration of KeepAlives by checking ttl.
Update documentation with instructions.

Use out_of_range exception on lease expiry

---

README.md
etcd/Client.hpp
etcd/KeepAlive.hpp
etcd/Response.hpp
etcd/Watcher.hpp
etcd/v3/AsyncWatchAction.hpp
src/Client.cpp
src/KeepAlive.cpp
src/Watcher.cpp
src/v3/AsyncWatchAction.cpp
tst/LockTest.cpp

The previous implementation is buggy when a lot of locks happen at the same time,
as the cpprestsdk's threadpool use a fixed number of thread for posix platform:
https://github.com/microsoft/cpprestsdk/blob/master/Release/src/pplx/threadpool.cpp#L198

Fixes lock, and the underlying keepalive implmentation.

---

vcpkg/etcd-cpp-apiv3/CONTROL
vcpkg/etcd-cpp-apiv3/portfile.cmake

1) Minor update for vcpkg portfile so that the port can be installed on macOS. 
2) And update the portfile to use the latest release v0.2.1.

Minor update for vcpkg portfile so that the port can be installed on macOS

---

src/v3/Action.cpp

Also, another comment, if "\0xFF\0xFF" is passed in "string_plus_one" parameter, nul is returned, is this really what was expected?

Removing memory-leak, fixes #83.

---

README.md
etcd/Client.hpp
src/Client.cpp

Add an optional `target_name_override` to support multiple-endpoints with SSL.

---

README.md
etcd/Watcher.hpp
src/Watcher.cpp

Proposal that fixes #117. 
About my fix:
- Avoids recreate `etcd::Watcher` object when connection is lost, instead it reuses the object (avoiding dangling objects or thread exception when cancelling).
- Adds support to return a bool value to async wait callback `std::function<bool(bool)> wait_callback` that it's used to recreate or cancel watcher.

Fixes the watcher reconnect issue

---

README.md
etcd/Watcher.hpp
etcd/v3/AsyncWatchAction.hpp
src/Watcher.cpp
src/v3/AsyncWatchAction.cpp
tst/RewatchTest.cpp
tst/WatcherTest.cpp

Address https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/73, https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/pull/76, https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/117 and https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/pull/118.
Revoke #118 as well.

Revisit the watcher's reconnect functionality. 

---

src/SyncClient.cpp

The `calloc` crash happens inside the the grpc's `AsyncNext`.
Resolves the random failure of MacOS.

No timeout for leaserevoke.

---

etcd/Client.hpp
etcd/KeepAlive.hpp
etcd/SyncClient.hpp
etcd/v3/AsyncLeaseAction.hpp
src/KeepAlive.cpp
src/v3/AsyncLeaseAction.cpp

Resolves #127, and replaces #128.

Enable grpc timeout support in keepalive's refresh.

---

CMakeLists.txt

if we use `etcd-cpp-apiv3` as submodule, we don't need to test `etcd-cpp-apiv3`.
in `CMakeLists.txt`
```
enable_testing()
add_subdirectory(src)
add_subdirectory(tst)
```
this code force to set `add_test()` and maybe make the project failed to `unit tests`.
Signed-off-by: zhang.han <dalezh@163.com>

build: as submodule, cancel `add_test()`

---

etcd/Client.hpp
src/Client.cpp
tst/LockTest.cpp

Resolves #139.
Lock is special, as it may cause the thread resources (in the pplx thread pool) to be exhausted.

Add a sync variant of lock on async client.

---

.github/workflows/centos-latest.yml
CMakeLists.txt
src/CMakeLists.txt
tst/CMakeLists.txt

Per abseil support policy, c++11 got dropped, thus updating `use_cxx11` to `use_cxx14` so that we can build from source with latest abseil
```
/opt/homebrew/include/absl/base/policy_checks.h:79:2: error: "C++ versions less than C++14 are not supported."
^
```
relates to https://github.com/Homebrew/homebrew-core/pull/121718

build: update use_cxx11 to use_cxx14

---

src/v3/AsyncLeaseAction.cpp
src/v3/AsyncWatchAction.cpp

The `grpc::Status` should be globally lived as the `Finish()` operation is asynchoronous.

Fixes the segmentation fault error in watcher

---

README.md
etcd/v3/action_constants.hpp
src/v3/Action.cpp
src/v3/AsyncGRPC.cpp
src/v3/action_constants.cpp
tst/ElectionTest.cpp

Fixes #224 by
- Fixes the extra `Read()` as we only support `WaitOnce()`.
- Fixes the behavior of `CancelObserve()`.
- Add a test case and revisit the example README.

Fixes the implementation of Observe()

---

src/v3/Action.cpp
src/v3/AsyncGRPC.cpp
tst/WatcherTest.cpp

- Fixes #219
- Related to #223

Assign a unique watch id for each watcher during creation

---

src/KeepAlive.cpp
tst/KeepAliveTest.cpp

KeepAlive: auto grant a new lease if 0 is given as lease id

---

src/CMakeLists.txt
src/SyncClient.cpp

When I [Update](https://github.com/microsoft/vcpkg/pull/32747) etcd-cpp-apiv3 version from 0.14.2 to 0.15.2, I get two build error:
````
fatal error LNK1107: invalid or corrupt file: cannot read at 0x330
````
````
error: use of undeclared identifier 'IPPROTO_TCP'
````
The first error was because the target `etcd-cpp-api-core-objects` linked the wrong `libprotobufd.dll` file instead of the .lib file, I used the usage provided by vcpkg to link the correct .lib file to fix this error.
Another error was because `IPPROTO_TCP` was missing declaration `"<netinet/in.h>"`, I added it to fix this error.

Fix error LNK1107 and undeclared identifier 'IPPROTO_TCP'

---

CMakeLists.txt

Hi,
To compile protobuf, CMake needs to use the protoc and grpc-cpp-plugin in the host architecture.
Unfortunately by default the protoc and grpc-cpp-plugin are the one for the Target.
And since gRPC 1.52 they are explictly not exported when Cross Compiling to avoid architecture mismatch.
See: https://github.com/grpc/grpc/commit/831d2a6855da36998e24f46e6b2a5b6f6042ad1a
Fix this by looking at the correct program
See example. https://github.com/grpc/grpc/blob/master/examples/cpp/cmake/common.cmake#L54-L62

cmake: fix when cross compiling

---

src/KeepAlive.cpp
src/SyncClient.cpp

Hi, 
I was compiled it from the scratch with gcc (Debian 12.2.0-14) 12.2.0 with `-Wall` enabled and I got some error:
```
/opt/src/thirdparty/etcd-cpp-apiv3/src/KeepAlive.cpp:72:52: error: unused parameter 'handler' [-Werror=unused-parameter]
72 |     std::function<void(std::exception_ptr)> const& handler, int ttl,
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/opt/src/thirdparty/etcd-cpp-apiv3/src/SyncClient.cpp:150:1: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
150 | const bool authenticate(std::shared_ptr<grpc::Channel> const& channel,  
```
The first one is an actual error that can lead to bugs if the ctor will be used. The handler passed to the ctor was omitted by mistake.

Fixes compiler errors

---

src/KeepAlive.cpp

Fix: keepalive exit without any message due to clock drift

---

.github/workflows/build-test.yml
README.md
src/SyncClient.cpp
tst/EtcdResolverTest.cpp

Enable ipv6 endpoints support

---

src/v3/AsyncGRPC.cpp
tst/EtcdSyncTest.cpp

Hi team,
This MR addresses the behavior mismatch mentioned in https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/issues/266
Have passed the `EtcdSyncTest`

Fix/add failure behavior #266

---

src/Value.cpp

This is exposed when compiling for musl platforms where this header is not included indirectly.

include stdint.h for int64_t types

---

README.md

remove  rm_if interface param: value in README.md
rm_if define as below:
```
/**
* Removes a single key but only if it has a specific value. Fails if the key
* does not exists or the its value differs from the expected one.
* @param key is the key to be deleted
*
* @return Returns etcdv3::ERROR_KEY_NOT_FOUND if the key does not exist.
*/
pplx::task<Response> rm_if(std::string const& key,
std::string const& old_value);
/**
* Removes an existing key only if it has a specific modification index value.
* Fails if the key does not exists or the modification index of it differs
* from the expected one.
* @param key is the key to be deleted
* @param old_index is the expected index of the existing value
*
* @return Returns etcdv3::ERROR_KEY_NOT_FOUND if the key does not exist.
*/ …
```

doc:remove rm_if interface param: value in README.md

---

src/SyncClient.cpp
tst/EtcdResolverTest.cpp

Problem Summary:
Now the etcd client  address do not support host format  such as http://[ipv6]:port. 
and [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2)   
```
A host identified by an Internet Protocol literal address, version 6
[[RFC3513](https://datatracker.ietf.org/doc/html/rfc3513)] or later, is distinguished by enclosing the IP literal
within square brackets ("[" and "]").  This is the only place where
square bracket characters are allowed in the URI syntax.  In
anticipation of future, as-yet-undefined IP literal address formats,
an implementation may use an optional version flag to indicate such a
format explicitly rather than rely on heuristic determination.
IP-literal = "[" ( IPv6address / IPvFuture  ) "]"
```
the ipv6 address  is distinguished by …

feature:support  ipv6 address

---

src/v3/Action.cpp

Latest GRPC >= 2.66 has dropped GRPC_ASSERT macro [1]
[1] https://github.com/grpc/grpc/commit/0e23c2259da967a037e839e80cafd62bc6f9f68e
Upstream-Status: Pending

Replacing GPR_ASSERT with c assert

---

etcd/v3/Member.hpp

Etcd compiles successfully using gcc version 9.4.0, but fails when using version 13.3.0.
The reason why gcc works with version 9.4.0 is that the \<string\> include the \<char_traits.h\>  that already include \<cstdint\>.
However, in version 13.3.0 of gcc, the  \<char_traits.h\> header file conditionally includes cstdint
Therefore, including \<cstdint\> in Member.hpp is able to solve this problem, which is also in line with the principle of include-what-you-use.
Related issue: #297

Fix uint64_t type error with gcc 13.3.
